import React, { lazy, Suspense, useState } from 'react';
import { ArrowRight, Orbit, Eye, EyeOff, LoaderCircle } from 'lucide-react';
const Planet = lazy(() => import('./memory/Planet').then(m => ({ default: m.Planet })));
const Atmosphere = lazy(() => import('./memory/Atmosphere').then(m => ({ default: m.Atmosphere })));
interface Props { isSetup: boolean; isNewUser?: boolean; onLogin: (pass: string) => void; onRegister: (pass: string) => void; onReset: () => void; onTestBypass?: () => void; errorMsg?: string | null; isLoading?: boolean; }
export const LockScreen: React.FC<Props> = ({ onLogin, onRegister, onTestBypass, errorMsg, isLoading }) => {
  const [register, setRegister] = useState(false), [pass, setPass] = useState(''), [confirm, setConfirm] = useState(''), [visible, setVisible] = useState(false), [error, setError] = useState('');
  return <div className="entry-gate"><Suspense fallback={null}><Atmosphere atmosphere="aurora" seed={1335} subdued /></Suspense><header><div className="wordmark"><Orbit size={28} strokeWidth={1.4} /><span>in mind<span className="brand-dot">.</span></span></div><span className="eyebrow">A PRIVATE MEMORY COLLECTION</span></header><main className="gate-layout"><section className="gate-art"><span className="eyebrow">EVERY LITTLE THING, IN ORBIT.</span><h1>给回忆，<br />一个<em>小宇宙。</em></h1><Suspense fallback={<div className="planet-loading">IN MIND</div>}><Planet compact seed={1335} /></Suspense><span className="gate-art-note">照片 · 手记 · 心情 · 偶然同频</span></section><section className="gate-form"><span className="eyebrow">{register ? 'MAKE ROOM FOR A MEMORY' : 'WELCOME BACK TO YOUR ORBIT'}</span><h2>{register ? '留一个专属暗号。' : '回到你的记忆里。'}</h2><p>{register ? '暗号是进入记录的凭证，请妥善保存。' : '用原来的暗号，打开那些留在心里的日子。'}</p><form onSubmit={e => { e.preventDefault(); setError(''); if (register && !/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).{6,}$/.test(pass.trim())) { setError('暗号至少 6 位，包含大小写字母、数字和符号。'); return; } if (register && pass !== confirm) { setError('两次暗号不一致。'); return; } register ? onRegister(pass) : onLogin(pass); }}><label>专属暗号<div className="pass-field"><input autoComplete={register ? 'new-password' : 'current-password'} required type={visible ? 'text' : 'password'} value={pass} onChange={e => setPass(e.target.value)} placeholder="输入你的暗号" /><button type="button" aria-label={visible ? '隐藏暗号' : '显示暗号'} onClick={() => setVisible(!visible)}>{visible ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label>{register && <label>再确认一次<input type="password" required autoComplete="new-password" value={confirm} onChange={e => setConfirm(e.target.value)} placeholder="再次输入暗号" /></label>}{(error || errorMsg) && <p className="inline-notice" role="alert">{error || errorMsg}</p>}<button className="primary-button" type="submit" disabled={isLoading}>{isLoading ? <LoaderCircle size={18} className="spin" /> : <ArrowRight size={18} />}{isLoading ? '正在连接…' : register ? '创建我的空间' : '打开我的记忆'}</button></form><button className="text-button gate-switch" disabled={isLoading} onClick={() => { setRegister(!register); setError(''); setPass(''); setConfirm(''); }}>{register ? '已有暗号，返回登录' : '第一次来？创建自己的空间'}<ArrowRight size={14} /></button><div className="gate-local"><button onClick={onTestBypass} disabled={isLoading}>先在本机体验 <ArrowUpRightIcon /></button><span>体验记录只在这台设备，不写入云端。</span></div></section></main><footer><span>IN MIND — 把生活，收进自己的轨道。</span><span>EST. 2026</span></footer></div>;
};
function ArrowUpRightIcon() { return <ArrowRight size={15} style={{ transform: 'rotate(-45deg)' }} />; }
